# Generated by Django 5.2.6 on 2025-09-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(db_column="about_first_name", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(db_column="about_last_name", max_length=100),
                ),
                ("email", models.EmailField(db_column="about_email", max_length=254)),
                ("phone", models.CharField(db_column="about_phone", max_length=20)),
                ("country", models.CharField(db_column="about_country", max_length=50)),
                ("city", models.CharField(db_column="about_city", max_length=50)),
                (
                    "address",
                    models.CharField(db_column="about_address", max_length=200),
                ),
                (
                    "image",
                    models.ImageField(db_column="about_image", upload_to="avatars/"),
                ),
                ("detail", models.TextField(db_column="about_detail")),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("subtitle", models.CharField(max_length=150)),
                ("detail", models.TextField()),
                ("start", models.CharField(max_length=50)),
                ("end", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("subtitle", models.CharField(max_length=150)),
                ("detail", models.TextField()),
                ("start", models.CharField(max_length=50)),
                ("end", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(max_length=200)),
                ("keywords", models.CharField(max_length=300)),
                ("maintenance", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook", models.URLField()),
                ("twitter", models.URLField()),
                ("instagram", models.URLField()),
                ("linkedin", models.URLField()),
                ("github", models.URLField()),
            ],
        ),
    ]
