# Generated by Django 5.2.6 on 2025-09-19 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={"verbose_name": "Person", "verbose_name_plural": "About"},
        ),
        migrations.AlterModelOptions(
            name="education",
            options={"verbose_name": "Education", "verbose_name_plural": "Education"},
        ),
        migrations.AlterModelOptions(
            name="settings",
            options={"verbose_name": "Setting", "verbose_name_plural": "Settings"},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"verbose_name": "Skill", "verbose_name_plural": "Skills"},
        ),
        migrations.AlterModelOptions(
            name="socialmedia",
            options={
                "verbose_name": "Social Media",
                "verbose_name_plural": "Social Media",
            },
        ),
    ]
