# Generated by Django 5.2.6 on 2025-09-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_about_options_alter_education_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Unknown", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Unknown", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(default="No description")),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Unknown", max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Settings",
        ),
        migrations.DeleteModel(
            name="SocialMedia",
        ),
        migrations.AlterModelOptions(
            name="about",
            options={},
        ),
        migrations.AlterModelOptions(
            name="education",
            options={},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={},
        ),
        migrations.RemoveField(
            model_name="about",
            name="city",
        ),
        migrations.RemoveField(
            model_name="about",
            name="country",
        ),
        migrations.RemoveField(
            model_name="about",
            name="detail",
        ),
        migrations.RemoveField(
            model_name="about",
            name="image",
        ),
        migrations.RemoveField(
            model_name="education",
            name="detail",
        ),
        migrations.RemoveField(
            model_name="education",
            name="end",
        ),
        migrations.RemoveField(
            model_name="education",
            name="start",
        ),
        migrations.RemoveField(
            model_name="education",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="education",
            name="title",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="detail",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="end",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="start",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="subtitle",
        ),
        migrations.AddField(
            model_name="about",
            name="about_text",
            field=models.TextField(default="No description"),
        ),
        migrations.AddField(
            model_name="about",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="about",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="about",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="about",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="date",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="education",
            name="degree",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="education",
            name="field",
            field=models.CharField(default="Unknown", max_length=200),
        ),
        migrations.AddField(
            model_name="education",
            name="gpa",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="education",
            name="school",
            field=models.CharField(default="Unknown", max_length=200),
        ),
        migrations.AddField(
            model_name="experience",
            name="company",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="experience",
            name="date",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="experience",
            name="description",
            field=models.TextField(default="No description"),
        ),
        migrations.AddField(
            model_name="experience",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="about",
            name="address",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="about",
            name="email",
            field=models.EmailField(default="unknown@example.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="about",
            name="first_name",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AlterField(
            model_name="about",
            name="last_name",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AlterField(
            model_name="about",
            name="phone",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AlterField(
            model_name="experience",
            name="title",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
