# Generated by Django 4.2.3 on 2025-09-23 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_award_certificate_interest_language_delete_settings_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Award",
        ),
        migrations.RemoveField(
            model_name="about",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="about",
            name="twitter",
        ),
    ]
