# Generated by Django 4.2.3 on 2025-10-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_delete_award_remove_about_facebook_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Unkown", max_length=200)),
                ("description", models.TextField(default="No description")),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("technologies", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="Language",
        ),
    ]
